In [10]:
import pandas as pd
import altair as alt
from altair import datum
import numpy as np

In [11]:
myJekyllDir = "C:/Users/larat/Desktop/LaraTerpetschnig.github.io/assets/json/"

# Plot 1

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/LaraTerpetschnig/LaraTerpetschnig.github.io/refs/heads/main/data/student-por.csv", sep=';')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [13]:
df_filtered = df[(df['Fjob'] != "other") & (df["Mjob"] != "other")]
data = pd.pivot_table(df_filtered, values='G3', index='Fjob', columns='Mjob', aggfunc='mean') 
data

Mjob        at_home     health   services    teacher
Fjob
at_home   11.833333   9.000000  11.142857  12.500000
health    11.000000  13.777778  11.000000  13.000000
services  10.555556  12.533333  11.779661  12.952381
teacher   11.000000  16.000000  14.125000  14.375000

In [14]:
data = data.reset_index().rename_axis(None, axis=1)
data

       Fjob    at_home     health   services    teacher
0   at_home  11.833333   9.000000  11.142857  12.500000
1    health  11.000000  13.777778  11.000000  13.000000
2  services  10.555556  12.533333  11.779661  12.952381
3   teacher  11.000000  16.000000  14.125000  14.375000

In [15]:
data_melted = data.melt(id_vars=['Fjob'], value_vars=['at_home', 'health', 'services', 'teacher'])
data_melted.rename({'variable':'Mjob'}, axis=1, inplace=True)
data_melted

        Fjob      Mjob      value
0    at_home   at_home  11.833333
1     health   at_home  11.000000
2   services   at_home  10.555556
3    teacher   at_home  11.000000
4    at_home    health   9.000000
5     health    health  13.777778
6   services    health  12.533333
7    teacher    health  16.000000
8    at_home  services  11.142857
9     health  services  11.000000
10  services  services  11.779661
11   teacher  services  14.125000
12   at_home   teacher  12.500000
13    health   teacher  13.000000
14  services   teacher  12.952381
15   teacher   teacher  14.375000

In [16]:
data_melted['value'].min(), data_melted['value'].max()

(9.0, 16.0)

In [17]:
# putting data transformations in chart 
select = alt.selection_point(fields=['Fjob', 'Mjob'])

heatmap = alt.Chart(df_filtered.pivot_table(values='G3', index='Fjob', columns='Mjob', aggfunc='mean') \
                    .reset_index().rename_axis(None, axis=1) \
                    .melt(id_vars=['Fjob'], value_vars=['at_home', 'health', 'services', 'teacher']) \
                    .rename({'variable':'Mjob', 'value':'Grade'}, axis=1),
    title='Click a tile to see grade distribution',
    height=250,
    width=250,
).mark_rect().encode(
    x=alt.X('Fjob').title("Father's Job"),
    y=alt.Y('Mjob').title("Mother's Job"),
    color=alt.Color('Grade').scale(domain=[9, 16], scheme='blues'),
    opacity=alt.when(select).then(alt.value(1)).otherwise(alt.value(0.4)),
).add_params(
    select
)

hist = alt.Chart(df_filtered).mark_bar().encode(
    x=alt.X("G3", bin=True),
    y='count(G3):Q'
).transform_filter(
    select
)

interactive_heatmap = hist | heatmap
interactive_heatmap

alt.HConcatChart(...)

In [18]:
interactive_heatmap.save(myJekyllDir + 'final_project_interactive_heatmap.json')

# Plot 2

In [ ]:
df2 = pd.read_csv("")