In [244]:
import pandas as pd
import altair as alt
alt.data_transformers.enable('vegafusion')
from geopy.geocoders import ArcGIS

In [245]:
df = pd.read_csv("https://github.com/UIUC-iSchool-DataViz/is445_data/raw/main/licenses_fall2022.csv")
df.head()

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Specialty/Qualifier,Controlled Substance Schedule,Delegated Controlled Substance Schedule,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason
0,1189509,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129446286,NOT RENEWED,N,NaN,EILEEN,NaN,SANTACRUZ,...,NaN,NaN,NaN,N,03/18/2022,NaN,NaN,NaN,NaN,NaN
1,801037,DETECTIVE BOARD,FIREARM CONTROL CARD,229030294.0,NOT RENEWED,N,NaN,DAGMAR,J,NORDLUND,...,NaN,NaN,NaN,N,08/16/2006,NaN,NaN,NaN,NaN,NaN
2,365129,COSMO,LICENSED COSMETOLOGIST,11053076.0,NOT RENEWED,N,NaN,RADOJE,NaN,ZELENOVIC,...,NaN,NaN,NaN,N,05/26/2006,NaN,NaN,NaN,NaN,NaN
3,595427,COSMO,LICENSED COSMETOLOGIST,11295645.0,ACTIVE,N,NaN,BECKY SUE,L,BURROUGHS,...,NaN,NaN,NaN,N,11/12/2021,NaN,NaN,NaN,NaN,NaN
4,653668,COSMO,LICENSED NAIL TECHNICIAN,169006247,NOT RENEWED,N,NaN,BILL G,L,LETNER,...,NaN,NaN,NaN,N,05/30/2006,NaN,NaN,NaN,NaN,NaN

In [246]:
df['License Type'].unique()

array(['DETECTIVE BOARD', 'COSMO', 'FUNERAL AND EMBALMER', 'DENTAL',
       'DESIGN FIRM', 'LIMITED LIABILITY CO', 'ATHLETIC TRAINER',
       'DIETETIC AND NUTRITION', 'APPRAISAL', 'MASSAGE LICENSING BD',
       'ARCHITECT', 'ATHLETICS', 'MAR AND FAM THERAPIST', 'GEOLOGY',
       'HME AND SERVICES PROV', 'COLLECTION AGENCY',
       'ENVIRON. HLTH PRACT', 'HOME INSPECTOR', 'LAND SURVEYOR BOARD',
       'CLIN PSYCHOLOGIST', 'INTERIOR DESIGN', 'LANDSCAPE ARCHITECT',
       'COMM ASSOC MGR', 'IDPR', 'MEDICAL BOARD', 'DETECT. DECEPTION',
       'AUCTIONEER', 'CEMETERY OVERSIGHT'], dtype=object)

In [247]:
df['License Type'].value_counts()

License Type
DETECTIVE BOARD           4867
COSMO                     3781
DENTAL                     739
FUNERAL AND EMBALMER        98
DIETETIC AND NUTRITION      73
DESIGN FIRM                 71
MASSAGE LICENSING BD        52
HOME INSPECTOR              46
COMM ASSOC MGR              37
CLIN PSYCHOLOGIST           24
INTERIOR DESIGN             22
COLLECTION AGENCY           21
LIMITED LIABILITY CO        21
ARCHITECT                   20
LAND SURVEYOR BOARD         17
HME AND SERVICES PROV       16
ATHLETICS                   15
MAR AND FAM THERAPIST       14
ATHLETIC TRAINER            14
ENVIRON. HLTH PRACT         13
IDPR                         9
GEOLOGY                      7
LANDSCAPE ARCHITECT          7
MEDICAL BOARD                6
APPRAISAL                    5
DETECT. DECEPTION            2
AUCTIONEER                   2
CEMETERY OVERSIGHT           1
Name: count, dtype: int64

In [248]:
df['Location'] = df['City'].str.cat(df['State'], sep=', ')
df.head()

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Controlled Substance Schedule,Delegated Controlled Substance Schedule,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason,Location
0,1189509,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129446286,NOT RENEWED,N,NaN,EILEEN,NaN,SANTACRUZ,...,NaN,NaN,N,03/18/2022,NaN,NaN,NaN,NaN,NaN,"CHICAGO, IL"
1,801037,DETECTIVE BOARD,FIREARM CONTROL CARD,229030294.0,NOT RENEWED,N,NaN,DAGMAR,J,NORDLUND,...,NaN,NaN,N,08/16/2006,NaN,NaN,NaN,NaN,NaN,"ELGIN, IL"
2,365129,COSMO,LICENSED COSMETOLOGIST,11053076.0,NOT RENEWED,N,NaN,RADOJE,NaN,ZELENOVIC,...,NaN,NaN,N,05/26/2006,NaN,NaN,NaN,NaN,NaN,"CHICAGO, IL"
3,595427,COSMO,LICENSED COSMETOLOGIST,11295645.0,ACTIVE,N,NaN,BECKY SUE,L,BURROUGHS,...,NaN,NaN,N,11/12/2021,NaN,NaN,NaN,NaN,NaN,"SCHAUMBURG, IL"
4,653668,COSMO,LICENSED NAIL TECHNICIAN,169006247,NOT RENEWED,N,NaN,BILL G,L,LETNER,...,NaN,NaN,N,05/30/2006,NaN,NaN,NaN,NaN,NaN,"CHICAGO, IL"

In [249]:
df_nt = df[df["Description"] == 'LICENSED NAIL TECHNICIAN']

In [250]:
df_nt = df_nt[df_nt.State == "IL"]

In [251]:
ag = ArcGIS()

In [252]:
def geocoding_lat(location):
    return ag.geocode(location).latitude

In [253]:
def geocoding_long(location):
    return ag.geocode(location).longitude

In [254]:
unique_locations = df_nt['Location'].unique()
d = dict(zip(unique_locations, pd.Series(unique_locations).apply(lambda x : geocoding_lat(x))))
df_nt['latitude'] = df_nt['Location'].map(d)

In [255]:
d = dict(zip(unique_locations, pd.Series(unique_locations).apply(lambda x : geocoding_long(x))))
df_nt['longitude'] = df_nt['Location'].map(d)

In [256]:
df_nt.head()

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason,Location,latitude,longitude
4,653668,COSMO,LICENSED NAIL TECHNICIAN,169006247,NOT RENEWED,N,NaN,BILL G,L,LETNER,...,N,05/30/2006,NaN,NaN,NaN,NaN,NaN,"CHICAGO, IL",41.883229,-87.632398
21,623882,COSMO,LICENSED NAIL TECHNICIAN,169007844.0,NOT RENEWED,N,NaN,NaN,NaN,NaN,...,N,12/12/2016,NaN,NaN,NaN,NaN,NaN,"DES PLAINES, IL",42.042297,-87.889320
36,657140,COSMO,LICENSED NAIL TECHNICIAN,169026124,ACTIVE,N,NaN,WALTER B,V,BUSSE,...,N,10/06/2020,NaN,NaN,NaN,NaN,NaN,"PALATINE, IL",42.110415,-88.043769
52,622200,COSMO,LICENSED NAIL TECHNICIAN,169009109.0,INACTIVE,N,NaN,MARLENE LEVIN,NaN,GRABER,...,N,05/30/2006,NaN,NaN,NaN,NaN,NaN,"PEORIA, IL",40.694592,-89.590362
53,673688,COSMO,LICENSED NAIL TECHNICIAN,169026286,ACTIVE,N,NaN,NaN,B,NaN,...,N,08/24/2020,NaN,NaN,NaN,NaN,NaN,"BERWYN, IL",41.843284,-87.791872

In [257]:
df_nt['License Status'].value_counts()

License Status
NOT RENEWED    138
ACTIVE         128
INACTIVE        10
Name: count, dtype: int64

In [262]:
df_nt.shape

(276, 34)

In [260]:
illinois_lines = alt.topo_feature("https://services2.arcgis.com/aIrBD8yn1TDTEXoz/arcgis/rest/services/Counties/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson", 
                            feature='geometry')
brush = alt.selection_interval()

background = alt.Chart(illinois_lines).mark_geoshape(
    fill='lightgray',
    stroke='white'
).properties(
    width=300,
    height=500
).project('albersUsa')

points = alt.Chart(df_nt[['latitude', 'longitude', 'License Status']]).mark_circle(
    size=30
).encode(
    longitude='longitude:Q',
    latitude='latitude:Q',
    color=alt.when(brush).then("License Status:N").otherwise(alt.value("black"))
).add_params(
    brush
)

bars = alt.Chart(df_nt[['latitude', 'longitude', 'License Status']]).mark_bar().encode(
    y='License Status:N',
    x='count(License Status):Q',
    color='License Status:N'
).transform_filter(
    brush
)

chart = background + points & bars
chart

alt.VConcatChart(...)

In [241]:
myJekyllDir = "C:/Users/larat/OneDrive/Desktop/LaraTerpetschnig.github.io/assets/json/"

In [261]:
chart.save(myJekyllDir + 'illinois_nail_tech.json')